remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

title: Patryk Loda
description: Smart contract security engineer at Binance. Working towards becoming a full time auditor.
logo: /assets/img/me.png

